FROM openjdk:8 
MAINTAINER superalbertini 
LABEL name="dockerfile-demo" version="1.0" author="superalbertini" 
COPY springboot-demo-0.0.1-SNAPSHOT dockerfile-image.jar 
CMD ["java","-jar","dockerfile-image.jar"]
